---
name: CI Build with tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11, 17, 21, 22 ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - uses: actions/setup-java@v4
        id: build_jdk
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: build distribution
        env:
          MAVEN_ARGS: "-Dbasepom.check.skip-enforcer=false -B -fae"
        run: |
          make install-fast

      - uses: actions/setup-java@v4
        id: test_jdk
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
          cache: maven

      - name: run tests
        env:
          MAVEN_ARGS: "-B -fae"
        run: |
          make run-tests
