name: ci

on:
  push:
    branches:
      - master
  pull-request:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-versions:
          - 11
          - 14
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build
        run: |
          ./mvnw -DskipTests=true -Dbasepom.check.skip-all=true -B -fae install
      - name: Test
        run: |
          ./mvnw -B -fae verify
      - name: Java 14 IT
        run: |
          ./mvnw -Pit-jdk14 -B -fae invoker:integration-test
      - name: Java 11 IT
        run: |
          ./mvnw -Pit-jdk11 -B -fae invoker:integration-test
      - name: Java 8 IT
        run: |
          ./mvnw -Pit-jdk8 -B -fae invoker:integration-test
