name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [11, 14]
        it-version: [8, 11, 14]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'zulu'
          cache: 'maven'
      - name: Build
        run: |
          ./mvnw -DskipTests=true -Dbasepom.check.skip-all=true -fae install
      - name: Test
        run: |
          ./mvnw -fae verify
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.it-version }}
          distribution: 'zulu'
          cache: 'maven'
      - name: Running IT on  Java ${{ matrix.it-version }}, built with Java ${{ matrix.java-version }}.
        run: |
          ./mvnw -Pit-jdk${{ matrix.it-version }} -fae invoker:integration-test invoker:verify
