---
name: Code style analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: run code checkers
        env:
          MAVEN_ARGS: "-B -fae"
        run: |
          make install-notests
